name: publish-nuget

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Build
      run: dotnet build Kafka.ParallelFlow.sln

    - name: Test
      run: dotnet test Kafka.ParallelFlow.Tests/Kafka.ParallelFlow.Tests.csproj --no-build --verbosity normal

    - name: Publish  
      uses: alirezanet/publish-nuget@v3.0.4
      with:
          PROJECT_FILE_PATH: Kafka.ParallelFlow/Kafka.ParallelFlow.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
